### ISSUE TITLE
Kernel, Stride combos that work

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/segmentation_zoo#20]
does it matter with target size?

- [ ] add to readme
- [ ] come up with solution (script?).. this is a fn of upsampling2d

**Comment by dbuscombe-usgs** [comment]
what i know....

kernel > 1
target size must be even, therefore upsampling has to be 2x2 (see original paper), but this makes some kernel/strides combos impossible

**Comment by dbuscombe-usgs** [comment]
I also think there may be fewer options when using deconvolution for upsampling
