### ISSUE TITLE
IoU testing

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/segmentation_zoo#21]
testing for `iou` 

OR 

using tf.keras.metrics implementation (https://www.tensorflow.org/api_docs/python/tf/keras/metrics/MeanIoU).

IoU is currently implemented:

https://github.com/dbuscombe-usgs/segmentation_zoo/blob/26cf2556bc980f8694037a99d669cabfbd164ac1/unet/model_imports.py#L804-L833

**Comment by dbuscombe-usgs** [comment]
Mean IoU now implemented as

```
    yt0 = tf.expand_dims(lbl, 0)
    yp0 = (est_label > 0.5).astype('float32')
    inter = np.count_nonzero(np.logical_and(np.equal(yt0, 1), np.equal(yp0, 1)))
    union = np.count_nonzero(tf.add(yt0, yp0))
    iou = np.where(np.equal(union, 0), 1., (inter/union))
```

which should now be equivalent to that used by keras. Now always returns scores < 1 on the Hatteras test dataset

**Comment by dbuscombe-usgs** [comment]
Mean dice is also now computed and reported by `plotcomp_n_getiou`
```
    smooth = 1.
    y_true_f = np.reshape(tf.dtypes.cast(y_true, tf.float32), [-1])
    y_pred_f = np.reshape(tf.dtypes.cast(y_pred, tf.float32), [-1])
    intersection = np.sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (np.sum(y_true_f) + np.sum(y_pred_f) + smooth)
```

tested on hatteras: gives reasonable values
