### ISSUE TITLE
make and test original Ronneberger Unet

### ISSUE THREAD

**Issue by dbuscombe-usgs** [dbuscombe-usgs/segmentation_zoo#25]
3x3 kernel
1x1 stride
2x2 upsample
number of filters=8

**Comment by dbuscombe-usgs** [comment]
{
  "MODEL": "unet",
  "KERNEL":3,
  "STRIDE":1,
  "FILTERS":8,
  "DROPOUT":0.0,
  "LOSS":"cat",
}

**Comment by ebgoldstein** [comment]
ok, for `"TARGET_SIZE": [768,1024],`, using the values above for the config, 

i get a tensor shape error: 

`ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 1536, 2048, 128), (None, 768, 1024, 64)]`

**Comment by ebgoldstein** [comment]
stride =2 works...

**Comment by ebgoldstein** [comment]
we can close this, and merge into #24
