### ISSUE TITLE
`train_model.py` plots fail with `RuntimeError: main thread is not in main loop`

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/segmentation_zoo#28]
Occasionally when running models back-to-back I will get the below error at the end of `train_model.py` when the  `plotcomp_n_getiou` fn is called
```
Exception ignored in: <function Image.__del__ at 0x7f096d0b74c0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
```
The result is that not all plots are rendered and saved

this seems to be a matplotlib issue.. i.e.

 https://stackoverflow.com/questions/27147300/matplotlib-tcl-asyncdelete-async-handler-deleted-by-the-wrong-thread

**Comment by dbuscombe-usgs** [comment]
`src\imports.py` now uses

```
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot
```

instead

` import matplotlib.pyplot as plt`

**Comment by dbuscombe-usgs** [comment]
I also added `K.clear_session()` at the bottom of the `counter` for-loop in `plotcomp_n_getiou`, which should help

you'll see changes in next commit

**Comment by ebgoldstein** [comment]
works!
