### ISSUE TITLE
AUG_LOOPS must be >2

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/segmentation_zoo#36]
Aug loop must be larger than 1, or else.....<cue the scary music>

**Comment by dbuscombe-usgs** [comment]
this will be fixed by adding

```
if AUG_LOOPS<2:
    AUG_LOOPS=2
```

before first time `AUG_LOOPS` is called

**Comment by dbuscombe-usgs** [comment]
appears in next commit, with updated README
