### ISSUE TITLE
Test Time Augmentation for Multiclass images

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/segmentation_zoo#9]
- horizontal flips
- vertical flips
- weighting

**Comment by dbuscombe-usgs** [comment]
3 aspects to this

- what type of augmentation (e.g. flips see above)
- what logic to combine augmented outputs? e.g. type of weighting? (equal weighting? weighting proportional to degree of transformation?)
- how to preserve raw outputs so any logic (above) can be reversed/changed in post-processing

The last point is another reason for storing model outputs and metadata as npz or similar

**Comment by dbuscombe-usgs** [comment]
test-time aug for multiclass outputs would now need to be implemented for both single-model `seg_images_in_folder` and ensemble model scripts, with a common `do_seg` function

**Comment by dbuscombe-usgs** [comment]
there are now two pred scripts ... seg_images_in_folder and ensemble_seg_images_in_folder - they are identical except for the number of models employed, and now use common functions defined in prediction_imports

**Comment by dbuscombe-usgs** [comment]
Sounds good, thanks

**Comment by ebgoldstein** [comment]
- [ ] add to `do_seg` fn in `prediction_imports.py`
- [ ] add new input to `do_seg` (`TESTTIMEAUG`)
- [ ] put new input is in all calls of `do_seg` 
- [ ] if user does not specify TTA, it should be false

**Comment by ebgoldstein** [comment]
- [ ] add details to readme

**Comment by ebgoldstein** [comment]
hard voting is not implemented
